#!/usr/bin/env bash

filename=$1
w=$2
h=$3
x=$4
y=$5

preview() {
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
}

TEMPDIR=~/.cache

case "$(file -bL --mime-type "$filename")" in
text/*)
    batcat --force-colorization --paging=never --style=changes,numbers \
        --terminal-width $(($w-3)) "$filename" && false
    ;;
image/*)
    preview "$filename"
    ;;
application/pdf)
	thumbnail="$TEMPDIR/thumbnail.png"
	gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$filename" >/dev/null
    preview "$thumbnail"
	;;
video/*)
	thumbnail="$TEMPDIR/thumbnail.png"
	ffmpeg -y -i "$filename" -vframes 1 "$thumbnail"
    preview "$thumbnail"
	;;
font/*)
	thumbnail="$TEMPDIR/thumbnail.png"
	fontpreview -i "$filename" -o "$thumbnail"
	preview "$thumbnail"
	;;
    
*) lf_bat_preview "$file" ;;
esac

# TODO file types
#*.tar*) tar tf "$file" ;;
#*.zip) unzip -l "$file" ;;
#*.rar) unrar l "$file" ;;
#*.7z) 7z l "$file" ;;
#*.svg)
#	thumbnail="$TEMPDIR/thumbnail.png"
#	convert "$file" "$thumbnail"
#	preview "$thumbnail"
#	;;

return 127 # nonzero retcode required for lf previews to reload
