#!/usr/bin/env bash

filename=$1
w=$2
h=$3
x=$4
y=$5

preview() {
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
}

TEMPDIR=~/.cache

case "$(file --brief --dereference --mime-type "$filename")" in
text/*)
    if which batcat >/dev/null; then
	batcat --force-colorization --paging=never --style=changes,numbers \
	    --terminal-width $(($w-3)) "$filename" && false
    elif which bat >/dev/null; then
	bat --force-colorization --paging=never --style=changes,numbers \
	    --terminal-width $(($w-3)) "$filename" && false
    else
	cat "$filename"
    fi
    ;;
image/*)
    preview "$filename"
    ;;
application/pdf)
	thumbnail="$TEMPDIR/thumbnail.jpg"
	gs -o "$thumbnail" -sDEVICE=jpeg -dLastPage=1 -dNOTRANSPARENCY "$filename" >/dev/null
    preview "$thumbnail"
	;;
video/*)
	# FFMPEG IMPLEMENTATION
    #thumbnail="$TEMPDIR/thumbnail.png"
    #ffmpeg -y -i "$filename" -ss 00:01:00 -frames:v 1 "$thumbnail" -s 0 -q 5
    
    # MTN IMPLEMENTATION
    thumbnail="$TEMPDIR/thumbnail.jpg"
    mtn "$filename" -c 3 -r 3 -O "$TEMPDIR" -x thumbnail -o .jpg -g 20 -f /usr/share/fonts/JetBrainsMono/JetBrainsMonoNerdFont-Regular.ttf -F 000000:30 --shadow=5 -w 2048
    preview "$thumbnail"
	;;
font/*)
	thumbnail="$TEMPDIR/thumbnail.png"
	fontpreview -i "$filename" -o "$thumbnail"
	preview "$thumbnail"
	;;
    
*) lf_bat_preview "$file" ;;
esac

# TODO file types
#*.tar*) tar tf "$file" ;;
#*.zip) unzip -l "$file" ;;
#*.rar) unrar l "$file" ;;
#*.7z) 7z l "$file" ;;
#*.svg)
#	thumbnail="$TEMPDIR/thumbnail.png"
#	convert "$file" "$thumbnail"
#	preview "$thumbnail"
#	;;

return 127 # nonzero retcode required for lf previews to reload
